#!/usr/bin/env python3
"""Convert an IDA / recomp function-list JSON into a viewer symbol map.

The call-trace viewer loads a plain-text symbol map: one `ADDRESS NAME` pair
per line. A PDB is a binary format the viewer can't read, and a recompiled
port's PDB only names original functions `sub_<addr>` anyway (no better than
the viewer's defaults). This converter instead reads a function list that
carries *real* names at original XBE addresses and emits a symbol map.

Accepted JSON schemas (auto-detected):
  * {"functions": [{"va": <int>, "name": <str>}, ...]}      (e.g. ida_truth)
  * [{"start": "0x...", "name": <str>}, ...]                (curated list)

Only functions whose name is not the default `sub_<hex>` are emitted, so the
map contains just the names worth showing. Simple MSVC-mangled names
(`?Method@Scope@@...`) are reduced to `Scope::Method`; complex ones (templates,
operators) are passed through unchanged.

Usage:
    python make_symbols.py <functions.json> [out.txt]
"""
import json
import os
import re
import sys

IDENT = re.compile(r'^[A-Za-z_][\w]*$')
SUBNAME = re.compile(r'^sub_[0-9A-Fa-f]+$')


def demangle_msvc(name):
    """Reduce a simple MSVC method name to Scope::Method; else return as-is."""
    if not name.startswith('?') or name.startswith('??'):
        return name
    end = name.find('@@')
    if end < 0:
        return name
    parts = name[1:end].split('@')
    if not parts or not all(IDENT.match(p) for p in parts):
        return name  # templates / special names: leave mangled
    method, scopes = parts[0], parts[1:]
    return '::'.join(list(reversed(scopes)) + [method])


def iter_functions(data):
    if isinstance(data, dict) and 'functions' in data:
        items = data['functions']
    elif isinstance(data, list):
        items = data
    else:
        sys.exit('error: unrecognized JSON shape (expected list or '
                 '{"functions": [...]})')
    for f in items:
        addr = f.get('va')
        if addr is None:
            addr = f.get('start', f.get('address'))
        if addr is None or 'name' not in f:
            continue
        va = addr if isinstance(addr, int) else int(str(addr), 0)
        yield va, f['name']


def main(json_path, out_path):
    with open(json_path, 'r', encoding='utf-8') as f:
        data = json.load(f)
    kept = skipped_default = 0
    with open(out_path, 'w', encoding='utf-8') as out:
        out.write('# symbol map generated by make_symbols.py from %s\n'
                  % os.path.basename(json_path))
        for va, name in iter_functions(data):
            if SUBNAME.match(name):
                skipped_default += 1
                continue
            out.write('%08X %s\n' % (va & 0xFFFFFFFF, demangle_msvc(name)))
            kept += 1
    print('wrote %s: %d named symbols (%d default sub_ names skipped)'
          % (out_path, kept, skipped_default))


if __name__ == '__main__':
    if len(sys.argv) < 2:
        sys.exit(__doc__)
    src = sys.argv[1]
    dst = sys.argv[2] if len(sys.argv) > 2 else \
        os.path.splitext(os.path.basename(src))[0] + '.symbols.txt'
    main(src, dst)
